[2025-10-02T08:00:05.799+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-02T08:00:05.805+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sentiment140_end2end_single.sf_debug_and_assert_table manual__2025-10-02T07:59:02.866757+00:00 [queued]>
[2025-10-02T08:00:05.810+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sentiment140_end2end_single.sf_debug_and_assert_table manual__2025-10-02T07:59:02.866757+00:00 [queued]>
[2025-10-02T08:00:05.810+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-02T08:00:05.816+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): sf_debug_and_assert_table> on 2025-10-02 07:59:02.866757+00:00
[2025-10-02T08:00:05.819+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1031) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-02T08:00:05.820+0000] {standard_task_runner.py:63} INFO - Started process 1033 to run task
[2025-10-02T08:00:05.820+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sentiment140_end2end_single', 'sf_debug_and_assert_table', 'manual__2025-10-02T07:59:02.866757+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/edaproject.py', '--cfg-path', '/tmp/tmpgdkkrck9']
[2025-10-02T08:00:05.822+0000] {standard_task_runner.py:91} INFO - Job 102: Subtask sf_debug_and_assert_table
[2025-10-02T08:00:05.843+0000] {task_command.py:426} INFO - Running <TaskInstance: sentiment140_end2end_single.sf_debug_and_assert_table manual__2025-10-02T07:59:02.866757+00:00 [running]> on host 9d9a5d472595
[2025-10-02T08:00:05.873+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sentiment140_end2end_single' AIRFLOW_CTX_TASK_ID='sf_debug_and_assert_table' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T07:59:02.866757+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-02T07:59:02.866757+00:00'
[2025-10-02T08:00:05.874+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-02T08:00:05.883+0000] {base.py:84} INFO - Using connection ID 'snowflake_default' for task execution.
[2025-10-02T08:00:05.884+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-02T08:00:05.884+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-02T08:00:06.919+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-02T08:00:07.050+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-02T08:00:07.177+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-02T08:00:07.338+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-02T08:00:07.450+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-02T08:00:07.452+0000] {logging_mixin.py:188} INFO - CONTEXT: [('EEB48403', 'AWS_US_WEST_2', 'ACCOUNTADMIN', 'COMPUTE_WH', 'YOUR_DB', 'PUBLIC')]
[2025-10-02T08:00:07.633+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-02T08:00:07.634+0000] {logging_mixin.py:188} INFO - TABLES: {'SENTIMENT140_CLEAN'}
[2025-10-02T08:00:07.634+0000] {connection.py:762} INFO - closed
[2025-10-02T08:00:07.694+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2025-10-02T08:00:07.781+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-02T08:00:07.783+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-02T08:00:07.795+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sentiment140_end2end_single, task_id=sf_debug_and_assert_table, run_id=manual__2025-10-02T07:59:02.866757+00:00, execution_date=20251002T075902, start_date=20251002T080005, end_date=20251002T080007
[2025-10-02T08:00:07.837+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-02T08:00:07.850+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-02T08:00:07.851+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
