[2025-10-02T08:00:08.408+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-02T08:00:08.414+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sentiment140_end2end_single.sf_check_rowcount manual__2025-10-02T07:59:02.866757+00:00 [queued]>
[2025-10-02T08:00:08.417+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sentiment140_end2end_single.sf_check_rowcount manual__2025-10-02T07:59:02.866757+00:00 [queued]>
[2025-10-02T08:00:08.417+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-02T08:00:08.421+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): sf_check_rowcount> on 2025-10-02 07:59:02.866757+00:00
[2025-10-02T08:00:08.425+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1034) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-02T08:00:08.425+0000] {standard_task_runner.py:63} INFO - Started process 1038 to run task
[2025-10-02T08:00:08.426+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sentiment140_end2end_single', 'sf_check_rowcount', 'manual__2025-10-02T07:59:02.866757+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/edaproject.py', '--cfg-path', '/tmp/tmp3817a94z']
[2025-10-02T08:00:08.427+0000] {standard_task_runner.py:91} INFO - Job 103: Subtask sf_check_rowcount
[2025-10-02T08:00:08.451+0000] {task_command.py:426} INFO - Running <TaskInstance: sentiment140_end2end_single.sf_check_rowcount manual__2025-10-02T07:59:02.866757+00:00 [running]> on host 9d9a5d472595
[2025-10-02T08:00:08.485+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sentiment140_end2end_single' AIRFLOW_CTX_TASK_ID='sf_check_rowcount' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T07:59:02.866757+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-02T07:59:02.866757+00:00'
[2025-10-02T08:00:08.486+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-02T08:00:08.491+0000] {sql.py:276} INFO - Executing: 
            USE ROLE ACCOUNTADMIN;
            USE WAREHOUSE COMPUTE_WH;
            USE DATABASE YOUR_DB;
            USE SCHEMA PUBLIC;
            SELECT COUNT(*) AS ROW_COUNT FROM YOUR_DB.PUBLIC.SENTIMENT140_CLEAN;
        
[2025-10-02T08:00:08.495+0000] {base.py:84} INFO - Using connection ID 'snowflake_default' for task execution.
[2025-10-02T08:00:08.498+0000] {base.py:84} INFO - Using connection ID 'snowflake_default' for task execution.
[2025-10-02T08:00:08.499+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-02T08:00:08.499+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-02T08:00:09.529+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-02T08:00:09.530+0000] {sql.py:470} INFO - Running statement: USE ROLE ACCOUNTADMIN;, parameters: None
[2025-10-02T08:00:09.711+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-02T08:00:09.712+0000] {sql.py:479} INFO - Rows affected: 1
[2025-10-02T08:00:09.713+0000] {snowflake.py:407} INFO - Rows affected: 1
[2025-10-02T08:00:09.713+0000] {snowflake.py:408} INFO - Snowflake query id: 01bf6fc0-0306-9174-0000-00131e6751a5
[2025-10-02T08:00:09.713+0000] {sql.py:470} INFO - Running statement: USE WAREHOUSE COMPUTE_WH;, parameters: None
[2025-10-02T08:00:09.846+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-02T08:00:09.847+0000] {sql.py:479} INFO - Rows affected: 1
[2025-10-02T08:00:09.847+0000] {snowflake.py:407} INFO - Rows affected: 1
[2025-10-02T08:00:09.848+0000] {snowflake.py:408} INFO - Snowflake query id: 01bf6fc0-0306-92f7-0000-00131e67f025
[2025-10-02T08:00:09.848+0000] {sql.py:470} INFO - Running statement: USE DATABASE YOUR_DB;, parameters: None
[2025-10-02T08:00:09.999+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-02T08:00:09.999+0000] {sql.py:479} INFO - Rows affected: 1
[2025-10-02T08:00:09.999+0000] {snowflake.py:407} INFO - Rows affected: 1
[2025-10-02T08:00:09.999+0000] {snowflake.py:408} INFO - Snowflake query id: 01bf6fc0-0306-8f79-0000-00131e67c17d
[2025-10-02T08:00:10.000+0000] {sql.py:470} INFO - Running statement: USE SCHEMA PUBLIC;, parameters: None
[2025-10-02T08:00:10.602+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-02T08:00:10.604+0000] {sql.py:479} INFO - Rows affected: 1
[2025-10-02T08:00:10.604+0000] {snowflake.py:407} INFO - Rows affected: 1
[2025-10-02T08:00:10.605+0000] {snowflake.py:408} INFO - Snowflake query id: 01bf6fc0-0306-8fe9-0000-00131e677165
[2025-10-02T08:00:10.605+0000] {sql.py:470} INFO - Running statement: SELECT COUNT(*) AS ROW_COUNT FROM YOUR_DB.PUBLIC.SENTIMENT140_CLEAN;, parameters: None
[2025-10-02T08:00:10.823+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-02T08:00:10.824+0000] {sql.py:479} INFO - Rows affected: 1
[2025-10-02T08:00:10.825+0000] {snowflake.py:407} INFO - Rows affected: 1
[2025-10-02T08:00:10.826+0000] {snowflake.py:408} INFO - Snowflake query id: 01bf6fc0-0306-908d-0000-00131e6781c5
[2025-10-02T08:00:10.942+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-02T08:00:10.945+0000] {connection.py:762} INFO - closed
[2025-10-02T08:00:11.022+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2025-10-02T08:00:11.120+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-02T08:00:11.161+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sentiment140_end2end_single, task_id=sf_check_rowcount, run_id=manual__2025-10-02T07:59:02.866757+00:00, execution_date=20251002T075902, start_date=20251002T080008, end_date=20251002T080011
[2025-10-02T08:00:11.207+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-02T08:00:11.214+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
